### ISSUE TITLE
MPI file write error

### ISSUE THREAD

**Issue by mchandra** [ALaDyn/piccante#1]
Hi,

I've been trying to get 1d_wakefield case to run but it crashes with an mpi file write error. I've tried this on two machines which give different but related error messages:

Machine 1:

 **\* An error occurred in MPI_File_set_view
 **\* on a NULL file
 **\* MPI_ERR_FILE: invalid file
 **\* MPI_ERRORS_ARE_FATAL: your MPI job will now abort

Machine 2:

MPI_FILE_WRITE(84): Invalid file handle
  0: Invalid argument
  0: Invalid argument, error stack:

The error comes from a call to manager.callDiags() in main-1.cpp

I tried putting in 
# define DEGUG_NO_MPI_FILE_WRITE

in output_manager.h but it seems to have no effect.

Am I doing something wrong or might this be a bug?

**Comment by cenit** [comment]
Did you compile with or without Boost support? In fact, we use boost to check for folders where to write output files. If the folder doesn't exists and you didn't compile with boost support, the program execution would end in the way you discovered.
So, if you compile without Boost support, unfortunately you have to manually create one (or two) folders, defined at the beginning of the1d_wakefield.cpp source code, which are
#define DIRECTORY_OUTPUT "TEST"
#define DIRECTORY_DUMP "TEST"
In this case, to summarize, you have to manually create the TEST folder (mind the caps!), or recompile piccante defining the USE_BOOST symbol.
Please let me know if I can close this issue

**Comment by mchandra** [comment]
Thanks, that worked. All I had to do was 

make boost

You can go ahead and close this issue.
