### ISSUE TITLE
How to run different examples like before.

### ISSUE THREAD

**Issue by ChenMinQi** [ALaDyn/piccante#3]
Hi:
In two weeks ago, if I want to run different examples,I just change main-1.cpp,like this:

```
cp ./examples/2d_twostream.cpp main-1.cpp
make boost
./piccante(or mpirun -np 2 ./piccante)
```

But now, it seems like I must read parameters form json,like this:

```
rm inputPiccante.json
cp ./examples/inputPiccante-twostream.json inputPiccante.json
make boost
```

Since I don't know the means of some parameters in inputPiccante-twostream.json and how to write a json ,so I want to run different examples like before, in other words, change the main-1.cpp,
what should I do?

When I get the results,it is storaged using a binary file.So I need to download "tools-piccante" and compile it. But there is no newfield_reader.cpp in tools-piccante. Is newreader.cpp equivalent to newfield_reader.cpp？ I used newreader.cpp to convert binary file to txt, but I don't know why the z always equal 0. what should I do?

Thanks！

**Comment by ChenMinQi** [comment]
The error, Segmentation fault, it is caused because of insufficient memory.Decreasing NCell(for example: 32*32*32),can eliminate this error.

**Comment by cenit** [comment]
you can always replace the main-1.cpp with the one coming from an older .cpp example. If anything is broken please report it.

For what concern the z you see in the .txt, is your simulation 2D or 3D?
