### ISSUE TITLE
move std::random to boost::random

### ISSUE THREAD

**Issue by cenit** [ALaDyn/piccante#4]
We should go back to using boost instead of C++11 features, since we can not afford loosing some HPC architectures in which C++11 is considered too new to be implemented.
This should be really easy, since the two generators are very close
Example for boost

```
boost::mt19937 generator;
boost::normal_distribution<> normal(0,1);
boost::variate_generator<boost::mt19937&,boost::normal_distribution<> > rng(generator, normal);
```

**Comment by lucafedeli88** [comment]
I agree...

**Comment by sgatto** [comment]
check if it is now fixed

**Comment by cenit** [comment]
fixed. Thanks @sgatto
