### ISSUE TITLE
Normalization of scale length l_0 and Calculation of no. of particles.

### ISSUE THREAD

**Issue by shivanichoudhary** [ALaDyn/piccante#6]
Hello,

I am trying to run 1d_wakefield case for different parameters and want to know how laser pulse amplitude is being normalized using scale length. As, whenever i change the value to amplitude the pulse gets multiplied with 6. 
Also for 1d_TNSA case if we run the code than it shows error for particles in plasma 2(ELE2 and ION2) which says
WARNING: ELE 2 /ION 2 is not allocated. 
Also, calculating no. of particle as ELE1 45000 and ION1 15000.
could you please tell me how these particles are being calculated and how to remove warning issue.

**Comment by sgatto** [comment]
Hello,
The normalisation can be explained simply from the last page of the documentation. Even if the documents needs to be updated for the use of the input file, all the normalisations still hold.
Can you send us the input file (.json) that you're using? Are you using the old main file?

If the laser amplitude is set to 1 the fields are 2 pi.

Thanks
Andrea Sgattoni

7 giu 2016, 16:25 +0200, shivanichoudharynotifications@github.com, ha scritto:
