### ISSUE TITLE
Linking errors

### ISSUE THREAD

**Issue by joymkj** [ALaDyn/piccante#7]
Hello,
Trying to run an example, make boost returns tons of linking errors like,
obj/jsonparser.o: In function `jsonParser::setBoundaryConditions(Json::Value&, GRID*)':
jsonparser.cpp:(.text+0x1a40): undefined reference to `Json::Value::Value(Json::ValueType)'
jsonparser.cpp:(.text+0x1a60): undefined reference to `Json::Value::size() const'
jsonparser.cpp:(.text+0x1a82): undefined reference to `Json::Value::~Value()'
jsonparser.cpp:(.text+0x1b18): undefined reference to `Json::Value::operator[](int)'
...
What am I doing wrong?
Also, why does compiling the .cpp file with mipcc and -std=c++11 doesn't work? (I have very limited coding experience)

(Also I replaced #include <json/json.h> with #include <jsoncpp/json/json.h>)

**Comment by sgatto** [comment]
It seems that you don't have jsoncpp or that the linker does not find it.
What kind of system do you have? 
I already found some installation of C++11 that don't have jsoncpp for some reason

**Comment by cenit** [comment]
may I ask you how did you build piccante?
Please refer to these instructions: https://github.com/ALaDyn/piccante/blob/master/BUILD.md

it seems that you are using an old and deprecated toolchain, and you also miss the jsoncpp library in your system

**Comment by joymkj** [comment]
I did have the newest version of libjsoncpp-dev, libjsoncpp0.
I exactly followed the BUILD.md instructions, except I had to update Cmake in the process.
However, during building I noticed the message 
Could NOT find MKL (missing:  MKL_INCLUDE_DIR MKL_LIBRARY MKL_MINIMAL_LIBRARY) 
Could it be related to the issue?

**Comment by cenit** [comment]
The problem is that `make boost` is not necessary to do anymore (you told you did it). To build examples, you just have to do:
```
cmake .. -DBUILD_EXAMPLES=ON
cmake --build . --target install   
```
instead of just `cmake ..`, which skips examples.

For what concern MKL it is not a problem: at least one between FFTW or MKL must be found.
If the procedure continues, it means that it found FFTW (much more common)

**Comment by joymkj** [comment]
I solved the json issue by manually setting the path. I built the examples and got a .dir for them, and some files in the bin. How do I get the output files, like diag.dat etc?
If there a new user guide I'm missing?

**Comment by cenit** [comment]
The .dir folders are made during the building, you can discard them.
All the binaries are saved into the bin folder, the examples, being in the "examples" subfolder. You can run them :)
Please let me know if you have any other question, we will update the user guide as appropriate since it lacks some updates

**Comment by joymkj** [comment]
Thanks for your help so far. Hopefully this is the last issue :)
I found the files in bin/examples. They do not have a .bin extension though.
I made the tools-piccante, but could not find a reader.exe. Although there exists frogReader, lightReader etc. So I tried ./lightReader.exe piccante_1d_TNSA which gave me a blank .txt file. How do I get the outputs?

**Comment by cenit** [comment]
In the bin/example folder, you find the executables. Of course you have to *run* them before having the outputs!

to recap:
1. build the source code (using cmake, you obtain the executables in the bin folder, or bin/examples for the examples)
2. run the executable (from your shell, execute `cd bin/examples ; ./piccante_1d_TNSA` for example)
3. analyse the results (any of the produced file)

**Comment by joymkj** [comment]
Of course. My bad.
Thanks very much. Everything's working fine now :)
