### ISSUE TITLE
Confused in passing value to structures.h setLambda function

### ISSUE THREAD

**Issue by Shikhamis** [ALaDyn/piccante#9]
Hi team I am confused what should be the UNIT of value to be passed to 

setLambda function of structures.cpp class ?

Referring to the code blocks below 

  ```
laserPulse pulse1;
  pulse1.setGaussianPulse();
  pulse1.setWaist(4.0);  // What is the unit for the passed value 4.0 ??
  pulse1.setDurationFWHM(10.0);
  pulse1.setNormalizedAmplitude(0.5);
  pulse1.setCircularPolarization();
  pulse1.setPulseInitialPosition(-10.1);
  pulse1.setFocusPosition(0.0);
  pulse1.setLambda(1.0); // What is the unit for the passed value 1.0 ??
  pulse1.setFocusPosition(0.0);
```

The project source has no comments/documents on the UNIT for the values of these functions.

For example in above code 
`pulse1.setLambda(1.0); `
I am confused what should be the UNIT for value passed ? What should be the UNIT assumed for such function ??

It would be really helpful if you could provide me some explanation or some source/documentation where it is mentioned !

**Comment by sgatto** [comment]
In the pdf it is specified that the code uses an arbitrary length l_0 to
with all the quantity are normalized.
So if you want to refer all the length to  le wavelength of your laser you
simply have to set the lambda to 1 (lambda=l_0)
than all the other length will be referred, indirectly to lambda: e.g.
waist=4 means w=4*l_0 = 4*lambda (since lambda=l_0)
is this clear to you?


Il giorno mar 31 mar 2020 alle ore 16:01 Shikhamis <notifications@github.com>
ha scritto:

**Comment by sgatto** [comment]
in the last page of this document
https://github.com/ALaDyn/piccante/blob/master/doc/user_guide.pdf
you can find all the normalizations used in the code.
As you can see all normalized length are expressed as factor of l_0. lambda and the laser waist are expressed in terms of l_0 too

**Comment by Shikhamis** [comment]
Dear Andrea Sgattoni,

                                        Thank you for your response. Now i
have understood the normalization of each dimension with respect to lo
(scale length). But where to mention that arbitrary length of the lo in in
the code piccante?  i.e. if i want to keep the wavelength of the laser at
800nm then what should be the steps? should i assume scale length(lo) is
initially st to be 1 microns. Your response is valuable for me.
Regards,
Shikha

**Comment by jonyanjiang** [comment]
In my view, the code set 1 micron to be the default length. If you want change the laser parameters, then use the pointer. Like
`  pulse1.lambda0 = 0.8;`

**Comment by Shikhamis** [comment]
Thank you for your response. Now the point is clear.
